Add event emitter option to track progress of computations
iotaledger/ccurl.interface.js pull request #6
Opened 2017-12-06 00:12 UTC by anyong

If `callback` is not provided, the function returns an event emitter with event types `progress` and `done`.

Event descriptions:

```
curl.on('progress', (err, progress) => {
  // progress from 0 to 1
});

curl.on('done', (err, result) => {
  // error or resulting trytes
});
```

2017-12-30 13:50 UTC, anyong commented
@paulhandy @th0br0 Have either of you had a chance to review this?

2018-01-05 16:38 UTC, l3wi commented
@th0br0 Can you please review this?

2018-01-05 17:08 UTC, th0br0 requested changes

2018-01-05 17:08 UTC, th0br0 commented on index.js
> +    function reportProgress(count) {
never called?

2018-01-08 16:31 UTC, anyong commented on index.js
> +    function reportProgress(count) {
Fixed in f1651e4.

2018-01-08 19:22 UTC, th0br0 approved these changes

2018-01-08 19:39 UTC, merged